export type CardProcessingMasterModel = {
  id: string;
  requestNo: string;
  residentId: string;
  residentName: string;
  apartmentId: string;
  apartmentNo: string;
  projectCode: string;
  cardId: string;
  fullSerialNo: string;
  maskedSerialNo: string;
  reasonId: string;
  reason: string;
  feeAmount: number;
  currency: string;
  taxAmount: string;
  totalFee: number;
  paymentMethod: string;
  paymentStatus: "Paid" | "Pending" | "Failed" | string;
  isSuspended: boolean;
  replacementStatus: "Pending" | "In Process" | "Ready" | "Delivered" | "Rejected" | string;
  status: string;
  deliverySLAHours: string;
  assignedStaffRole?: string;
  approverId?: string;
  rejectionReason?: string;
  approvalHistory?: any[];
  active: boolean;
  isArchived: boolean;
  createdAt?: string;
  updatedAt?: string;
};
