import { Result } from "@/utility/result";
import { Failure } from "@/utility/failure";
import { Generator } from "@/utility/generator";
import { QRConfigurationMasterModel } from "@/models/qr-configuration-master-model";
import { QRConfigurationMasterRepository } from "@/repositories/qr-configuration-master-repository";

type Props = {
  qrConfigurationMasterRepository: QRConfigurationMasterRepository;
};

type Input = {
  id?: string;             // Database Primary Key (Edit mode me pass hota hai)
  qrConfigId?: string;     // Auto-generated ID (e.g. "QRC-101")
  expiryHours: number;
  isOneTimeScan?: boolean;
  isGateValidation?: boolean;
  isPdfRequired?: boolean;
  isActive?: boolean;
};

export class CreateQRConfigurationMasterService {
  protected _qrConfigurationMasterRepository: QRConfigurationMasterRepository;

  public constructor(props: Props) {
    this._qrConfigurationMasterRepository = props.qrConfigurationMasterRepository;
  }

  public async execute(input: Input): Promise<Result<string, Failure>> {
    const isActive = typeof input.isActive !== "undefined" ? Boolean(input.isActive) : true;
    const isOneTimeScan = Boolean(input.isOneTimeScan);
    const isGateValidation = Boolean(input.isGateValidation);
    const isPdfRequired = Boolean(input.isPdfRequired);

    // UPDATE LOGIC (Jab DB ki primary key 'input.id' pass ki gayi ho)
    if (input.id) {
      const existing = await this._qrConfigurationMasterRepository.get(input.id);
      if (existing) {
        existing.qrConfigId = input.qrConfigId || existing.qrConfigId;
        existing.expiryHours = Number(input.expiryHours) || existing.expiryHours;
        existing.isOneTimeScan = isOneTimeScan;
        existing.isGateValidation = isGateValidation;
        existing.isPdfRequired = isPdfRequired;
        existing.isActive = isActive;

        await this._qrConfigurationMasterRepository.Update(existing);
        return Result.ok(input.id);
      }
    }

    // CREATE LOGIC (Jab Naya Record banega tab DB ki primary key 'QR' prefix se generate hogi)
    const primaryKeyId = input.id || Generator.id("QR");
    const autoGeneratedConfigId = input.qrConfigId || Generator.id("QRC");

    const qrConfigModel = QRConfigurationMasterModel.make({
      id: primaryKeyId,                  // Primary Key -> QR-12345
      qrConfigId: autoGeneratedConfigId, // Auto-Generated Config ID -> QRC-12345
      expiryHours: Number(input.expiryHours),
      isOneTimeScan,
      isGateValidation,
      isPdfRequired,
      isActive,
      isArchived: false,
    });

    const validationBag = qrConfigModel.validate();
    if (validationBag.hasErrors()) {
      return Result.fail(Failure.validation(validationBag));
    }

    const record = qrConfigModel.getRecord();
    await this._qrConfigurationMasterRepository.Create(record as any);

    return Result.ok(qrConfigModel.get("id"));
  }
}